apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: ic-webapp
  labels:
    app: postgres
    env: prod
spec:
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector: 
    app: postgres
  type: ClusterIP

