apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
    env: prod
  name: postgres
  namespace: ic-webapp
spec:
  containers:
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector: 
      app: postgres
    type: ClusterIP
