apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-pvc
  namespace: ic-webapp
  labels:
    app: odoo 
    env: prod
spec:
  storageClassName: manual
  accessModes: 
    - ReadWriteMany
  resources:
    requests: 
      storage: 5Gi
