apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-pv
  namespace: ic-webapp
  labels:
    type: local
    env: prod
spec:
  storageClassName: manual
  capacity: 
    storage: 10Gi
  accessModes: 
    - ReadWriteMany
  hostPath:
    path: "/data_k8s/lib-odoo" 
